### ISSUE TITLE
error during OAuth - TypeError: undefined is not a function

### ISSUE THREAD

**Issue by timabell** [nhduy1985/linkedin-export-tool#6]
Not quite sure how I managed to trigger this, filing an issue for the record in case it happens again.

Had been changing the "Authorized Redirect URLs" list on LinkedIn, then when visiting [http://localhost:3001/oauth/linkedin](http://localhost:3001/oauth/linkedin) I got this:

```
TypeError: undefined is not a function
    at Object.getAccessToken (/home/tim/repo/linkedin-export-tool/node_modules/node-linkedin/lib/auth.js:69:24)
    at app.get.response (/home/tim/repo/linkedin-export-tool/app.js:17:19)
    at Layer.handle [as handle_request] (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/layer.js:95:5)
    at /home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/index.js:330:12)
    at next (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/home/tim/repo/linkedin-export-tool/node_modules/express/lib/middleware/init.js:33:5)
```

**Comment by timabell** [comment]
ah okay that's what I get for upgrading the linkedin dependency, it was a delayed effect it didn't break till I re-ran `npm insall`
